version: 2.1
parameters:
  image-tag:
    type: string
    default: "current"
  workingdir:
    type: string
    default: "~/main"
  username:
    type: string
    default: ""
  password:
    type: string
    default: ""
  admin-username:
    type: string
    default: ""
  admin-password:
    type: string
    default: ""

jobs:
  dev-uat:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    environment:
      IMAGETAG: << pipeline.parameters.image-tag >>
    steps:
      - run: echo "Image tag used was ${IMAGETAG}"
      - run: echo "$(pwd) == << pipeline.parameters.workingdir >>"
      - run: echo "username is << pipeline.parameters.username >>"
      - run: echo "password is << pipeline.parameters.password >>"

  uat-prod:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    steps:
      - when:
          condition:
            not:
              equal: [ "", << pipeline.parameters.username >> ]
          steps:
            - run: echo "username is << pipeline.parameters.admin-username >>"
            - run: echo "password is << pipeline.parameters.admin-password >>"
      - run: echo "Not printing username & password"

workflows:
  dev-workflow:
    when:
        not:
          equal: [ "", << pipeline.parameters.username >> ]
    jobs:
      - approve-dev:
          type: approval
      - dev-uat:
          requires:
            - approve-dev

  prod-workflow:
    when:
        not:
          equal: [ "", << pipeline.parameters.admin-username >> ]
    jobs:
      - approve-prod:
          type: approval
      - uat-prod:
          requires:
            - approve-prod
